platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod 'DynamicColor', '~> 2.4'
end

target 'SnappingStepper' do
  shared_pods
end

target 'SnappingStepperExample' do
  shared_pods
end

target 'Tests' do
  shared_pods
end

target 'UITests' do
  shared_pods
end
