platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod 'DynamicColor', '~> 3.1'
  pod 'StyledLabel', '~> 2.0'
end

target 'SnappingStepper' do
  shared_pods
end

target 'SnappingStepperExample' do
  shared_pods
end

target 'Tests' do
  shared_pods
end
